language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails40.gemfile
